// 游戏静态配置
const CONFIG = Object.freeze({
  baseClickValue: 1,
  buildingPriceGrowth: 1.15,

  buildings: [
    { id: 'cursor',      name: '小猴子',    emoji: '🖐️', baseCPS: 0.1,             basePrice: 15,                          desc: '灵活敏捷的猴爪，每10秒自动精准点击一次大香蕉。' },
    { id: 'grandma',     name: '猴子智者',   emoji: '🐵', baseCPS: 1,               basePrice: 100,                         desc: '德高望重的老猴王，精通千年传承的秘制香蕉烘焙技艺。' },
    { id: 'farm',        name: '猴子农工',   emoji: '🌾', baseCPS: 8,               basePrice: 1100,                        desc: '勤劳朴实的猴子农夫，在花果山的田地里种植各种香蕉作物。' },
    { id: 'mine',        name: '猴子矿工',   emoji: '⛏️', baseCPS: 47,              basePrice: 12000,                       desc: '身强力壮的猴子矿工，深入地下开采香蕉矿脉。' },
    { id: 'factory',     name: '猴子员工',   emoji: '🏭', baseCPS: 260,             basePrice: 130000,                      desc: '训练有素的猴子工人，在现代化流水线上高效批量生产香蕉。' },
    { id: 'bank',        name: '收银猴',     emoji: '💰', baseCPS: 1400,            basePrice: 1400000,                     desc: '精明能干的猴子会计，管理香蕉金库，让存款产生丰厚利息。' },
    { id: 'temple',      name: '萨满猴',     emoji: '🔮', baseCPS: 7800,            basePrice: 20000000,                    desc: '神秘莫测的猴子萨满，沟通远古香蕉之神，祈求无尽的香蕉祝福。' },
    { id: 'wizard',      name: '巫师猴',     emoji: '🪄', baseCPS: 44000,           basePrice: 330000000,                   desc: '法力高强的猴子巫师，在高塔中施展古老魔法召唤香蕉。' },
    { id: 'shipment',    name: '魔法猴',     emoji: '✨', baseCPS: 260000,          basePrice: 5100000000,                  desc: '腾云驾雾的魔法猴子，从遥远的香蕉星球运来最新鲜的香蕉。' },
    { id: 'alchemy',     name: '炼金术猴',   emoji: '⚗️', baseCPS: 1600000,         basePrice: 75000000000,                 desc: '博学多才的猴子炼金师，掌握将黄金转化为香蕉的禁忌秘术。' },
    { id: 'portal',      name: '宇航猴',     emoji: '🚀', baseCPS: 10000000,        basePrice: 1000000000000,               desc: '勇敢无畏的猴子宇航员，驾驶飞船穿越传送门探索香蕉宇宙。' },
    { id: 'timemachine', name: '猴子科学家', emoji: '⏰', baseCPS: 65000000,        basePrice: 14000000000000,              desc: '聪明绝顶的猴子科学家，发明时光机从过去和未来收集香蕉。' },
    { id: 'antimatter',  name: '爱因斯猴',   emoji: '⚛️', baseCPS: 430000000,       basePrice: 170000000000000,             desc: '最伟大的猴子物理学家，推导出将反物质转化为香蕉的公式。' },
    { id: 'prism',       name: '哆啦A猴',    emoji: '🌈', baseCPS: 2900000000,      basePrice: 2100000000000000,            desc: '来自22世纪的机器猫猴，用神奇口袋和光线制造无限香蕉。' },
    { id: 'chancemaker', name: '奥特猴',     emoji: '🌟', baseCPS: 21000000000,     basePrice: 26000000000000000,           desc: '来自M78星云的猴子战士，用光之力量带来源源不断的幸运香蕉。' },
    { id: 'fractal',     name: '变形猴刚',   emoji: '🔷', baseCPS: 150000000000,    basePrice: 310000000000000000,          desc: '强大的变形金刚猴，能将一块香蕉分裂成无数块相同的香蕉。' },
    { id: 'javascript',  name: 'java猴',     emoji: '💻', baseCPS: 1100000000000,   basePrice: 71000000000000000000,        desc: '精通编程的猴子程序员，直接从游戏代码中生成海量香蕉。' },
    { id: 'idleverse',   name: '猴子黑洞',   emoji: '🌌', baseCPS: 8300000000000,   basePrice: 12000000000000000000000,     desc: '吞噬一切的猴子黑洞，劫持其他闲置宇宙的生产并转化为香蕉。' },
    { id: 'cortex',      name: '六耳猕猴',   emoji: '🐒', baseCPS: 64000000000000,  basePrice: 1900000000000000000000000,   desc: '神通广大的六耳猕猴，能用强大意念将想象中的香蕉变为现实。' },
    { id: 'you',         name: '美猴王',     emoji: '👑', baseCPS: 510000000000000, basePrice: 310000000000000000000000000, desc: '齐天大圣孙悟空，所有猴子的领袖，是这一切香蕉奇迹的缔造者。' },
  ],

  upgrades: [
    // ── 点击力升级 ──────────────────────────────────
    { id: 'click_1', name: '灵猴利爪',  emoji: '🖐️', category: 'click',
      effect: { type: 'click_mult', value: 2 }, desc: '点击香蕉的价值 ×2',
      unlockAt: 0, cost: 100 },
    { id: 'click_2', name: '金刚护腕',  emoji: '🥊', category: 'click',
      effect: { type: 'click_mult', value: 2 }, desc: '点击香蕉的价值 ×2',
      unlockAt: 500, cost: 500 },
    { id: 'click_3', name: '左右开弓',  emoji: '🤲', category: 'click',
      effect: { type: 'click_mult', value: 2 }, desc: '点击香蕉的价值 ×2',
      unlockAt: 9000, cost: 10000 },
    { id: 'click_4', name: '千猴齐点',  emoji: '🐒', category: 'click',
      effect: { type: 'click_mult', value: 2 }, desc: '点击香蕉的价值 ×2',
      unlockAt: 9e4, cost: 1e5 },
    { id: 'click_5', name: '万猴奔腾',  emoji: '🌊', category: 'click',
      effect: { type: 'click_mult', value: 2 }, desc: '点击香蕉的价值 ×2',
      unlockAt: 9e5, cost: 1e6 },
    { id: 'click_6', name: '亿猴狂点',  emoji: '⚡', category: 'click',
      effect: { type: 'click_mult', value: 2 }, desc: '点击香蕉的价值 ×2',
      unlockAt: 9e8, cost: 1e9 },
    { id: 'click_7', name: '兆猴齐发',  emoji: '💥', category: 'click',
      effect: { type: 'click_mult', value: 2 }, desc: '点击香蕉的价值 ×2',
      unlockAt: 9e11, cost: 1e12 },
    // ── 全局产速升级 ─────────────────────────────────
    { id: 'cps_1', name: '香蕉加速',   emoji: '🚀', category: 'cps',
      effect: { type: 'cps_mult', value: 1.1 }, desc: '全局香蕉产速 ×1.1',
      unlockAt: 900, cost: 5000 },
    { id: 'cps_2', name: '香蕉倍增',   emoji: '✨', category: 'cps',
      effect: { type: 'cps_mult', value: 1.1 }, desc: '全局香蕉产速 ×1.1',
      unlockAt: 9000, cost: 50000 },
    { id: 'cps_3', name: '香蕉放大',   emoji: '🔮', category: 'cps',
      effect: { type: 'cps_mult', value: 1.1 }, desc: '全局香蕉产速 ×1.1',
      unlockAt: 9e4, cost: 5e5 },
    { id: 'cps_4', name: '香蕉指数',   emoji: '📈', category: 'cps',
      effect: { type: 'cps_mult', value: 1.1 }, desc: '全局香蕉产速 ×1.1',
      unlockAt: 9e5, cost: 5e6 },
    { id: 'cps_5', name: '香蕉对数',   emoji: '🧮', category: 'cps',
      effect: { type: 'cps_mult', value: 1.1 }, desc: '全局香蕉产速 ×1.1',
      unlockAt: 9e6, cost: 5e7 },
    { id: 'cps_6', name: '香蕉超算',   emoji: '💻', category: 'cps',
      effect: { type: 'cps_mult', value: 1.1 }, desc: '全局香蕉产速 ×1.1',
      unlockAt: 9e7, cost: 5e8 },

    // ── 小猴子 (cursor) 分级升级 ─────────────────────
    { id: 'cursor_t1', name: '初级猴爪',  emoji: '🤌', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'cursor', value: 2 },
      desc: '小猴子产速 ×2', unlockBuilding: { id: 'cursor', count: 1 }, unlockAt: 0, cost: 150 },
    { id: 'cursor_t2', name: '精灵猴爪',  emoji: '🖐️', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'cursor', value: 2 },
      desc: '小猴子产速 ×2', unlockBuilding: { id: 'cursor', count: 5 }, unlockAt: 0, cost: 1500 },
    { id: 'cursor_t3', name: '灵猴天赋',  emoji: '🙌', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'cursor', value: 2 },
      desc: '小猴子产速 ×2', unlockBuilding: { id: 'cursor', count: 25 }, unlockAt: 0, cost: 15000 },
    { id: 'cursor_t4', name: '万指齐发',  emoji: '👐', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'cursor', value: 2 },
      desc: '小猴子产速 ×2', unlockBuilding: { id: 'cursor', count: 50 }, unlockAt: 0, cost: 150000 },
    { id: 'cursor_t5', name: '神猴圣手',  emoji: '🦾', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'cursor', value: 2 },
      desc: '小猴子产速 ×2', unlockBuilding: { id: 'cursor', count: 100 }, unlockAt: 0, cost: 1500000 },

    // ── 猴子智者 (grandma) 分级升级 ──────────────────
    { id: 'grandma_t1', name: '祖传秘籍',  emoji: '📜', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'grandma', value: 2 },
      desc: '猴子智者产速 ×2', unlockBuilding: { id: 'grandma', count: 1 }, unlockAt: 0, cost: 1000 },
    { id: 'grandma_t2', name: '千年配方',  emoji: '🍯', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'grandma', value: 2 },
      desc: '猴子智者产速 ×2', unlockBuilding: { id: 'grandma', count: 5 }, unlockAt: 0, cost: 10000 },
    { id: 'grandma_t3', name: '长老凝香',  emoji: '🌿', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'grandma', value: 2 },
      desc: '猴子智者产速 ×2', unlockBuilding: { id: 'grandma', count: 25 }, unlockAt: 0, cost: 100000 },
    { id: 'grandma_t4', name: '神圣烘焙',  emoji: '🔥', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'grandma', value: 2 },
      desc: '猴子智者产速 ×2', unlockBuilding: { id: 'grandma', count: 50 }, unlockAt: 0, cost: 1000000 },
    { id: 'grandma_t5', name: '长老神谕',  emoji: '🌙', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'grandma', value: 2 },
      desc: '猴子智者产速 ×2', unlockBuilding: { id: 'grandma', count: 100 }, unlockAt: 0, cost: 10000000 },

    // ── 猴子农工 (farm) 分级升级 ─────────────────────
    { id: 'farm_t1', name: '肥沃田地',  emoji: '🌿', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'farm', value: 2 },
      desc: '猴子农工产速 ×2', unlockBuilding: { id: 'farm', count: 1 }, unlockAt: 0, cost: 11000 },
    { id: 'farm_t2', name: '香蕉丰收',  emoji: '🌽', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'farm', value: 2 },
      desc: '猴子农工产速 ×2', unlockBuilding: { id: 'farm', count: 5 }, unlockAt: 0, cost: 110000 },
    { id: 'farm_t3', name: '基因优化',  emoji: '🧬', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'farm', value: 2 },
      desc: '猴子农工产速 ×2', unlockBuilding: { id: 'farm', count: 25 }, unlockAt: 0, cost: 1100000 },
    { id: 'farm_t4', name: '超级作物',  emoji: '🌱', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'farm', value: 2 },
      desc: '猴子农工产速 ×2', unlockBuilding: { id: 'farm', count: 50 }, unlockAt: 0, cost: 11000000 },
    { id: 'farm_t5', name: '天降甘露',  emoji: '🌧️', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'farm', value: 2 },
      desc: '猴子农工产速 ×2', unlockBuilding: { id: 'farm', count: 100 }, unlockAt: 0, cost: 110000000 },

    // ── 猴子矿工 (mine) 分级升级 ─────────────────────
    { id: 'mine_t1', name: '矿脉探测',  emoji: '🔦', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'mine', value: 2 },
      desc: '猴子矿工产速 ×2', unlockBuilding: { id: 'mine', count: 1 }, unlockAt: 0, cost: 120000 },
    { id: 'mine_t2', name: '深层开采',  emoji: '💎', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'mine', value: 2 },
      desc: '猴子矿工产速 ×2', unlockBuilding: { id: 'mine', count: 5 }, unlockAt: 0, cost: 1200000 },
    { id: 'mine_t3', name: '爆破技术',  emoji: '💥', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'mine', value: 2 },
      desc: '猴子矿工产速 ×2', unlockBuilding: { id: 'mine', count: 25 }, unlockAt: 0, cost: 12000000 },
    { id: 'mine_t4', name: '晶体提炼',  emoji: '🔶', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'mine', value: 2 },
      desc: '猴子矿工产速 ×2', unlockBuilding: { id: 'mine', count: 50 }, unlockAt: 0, cost: 120000000 },
    { id: 'mine_t5', name: '香蕉地核',  emoji: '🌋', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'mine', value: 2 },
      desc: '猴子矿工产速 ×2', unlockBuilding: { id: 'mine', count: 100 }, unlockAt: 0, cost: 1200000000 },

    // ── 猴子员工 (factory) 分级升级 ──────────────────
    { id: 'factory_t1', name: '流水线改造',  emoji: '🏗️', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'factory', value: 2 },
      desc: '猴子员工产速 ×2', unlockBuilding: { id: 'factory', count: 1 }, unlockAt: 0, cost: 1300000 },
    { id: 'factory_t2', name: '自动化升级',  emoji: '🤖', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'factory', value: 2 },
      desc: '猴子员工产速 ×2', unlockBuilding: { id: 'factory', count: 5 }, unlockAt: 0, cost: 13000000 },
    { id: 'factory_t3', name: '质量管控',    emoji: '📊', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'factory', value: 2 },
      desc: '猴子员工产速 ×2', unlockBuilding: { id: 'factory', count: 25 }, unlockAt: 0, cost: 130000000 },
    { id: 'factory_t4', name: '工厂扩建',    emoji: '🏭', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'factory', value: 2 },
      desc: '猴子员工产速 ×2', unlockBuilding: { id: 'factory', count: 50 }, unlockAt: 0, cost: 1300000000 },
    { id: 'factory_t5', name: '超级工厂',    emoji: '⚡', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'factory', value: 2 },
      desc: '猴子员工产速 ×2', unlockBuilding: { id: 'factory', count: 100 }, unlockAt: 0, cost: 13000000000 },

    // ── 收银猴 (bank) 分级升级 ───────────────────────
    { id: 'bank_t1', name: '利息收益',  emoji: '📈', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'bank', value: 2 },
      desc: '收银猴产速 ×2', unlockBuilding: { id: 'bank', count: 1 }, unlockAt: 0, cost: 14000000 },
    { id: 'bank_t2', name: '高息账户',  emoji: '💳', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'bank', value: 2 },
      desc: '收银猴产速 ×2', unlockBuilding: { id: 'bank', count: 5 }, unlockAt: 0, cost: 140000000 },
    { id: 'bank_t3', name: '量化交易',  emoji: '📉', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'bank', value: 2 },
      desc: '收银猴产速 ×2', unlockBuilding: { id: 'bank', count: 25 }, unlockAt: 0, cost: 1400000000 },
    { id: 'bank_t4', name: '香蕉债券',  emoji: '🏦', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'bank', value: 2 },
      desc: '收银猴产速 ×2', unlockBuilding: { id: 'bank', count: 50 }, unlockAt: 0, cost: 14000000000 },
    { id: 'bank_t5', name: '宇宙银行',  emoji: '🌐', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'bank', value: 2 },
      desc: '收银猴产速 ×2', unlockBuilding: { id: 'bank', count: 100 }, unlockAt: 0, cost: 140000000000 },

    // ── 萨满猴 (temple) 分级升级 ─────────────────────
    { id: 'temple_t1', name: '香蕉祈祷',  emoji: '🙏', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'temple', value: 2 },
      desc: '萨满猴产速 ×2', unlockBuilding: { id: 'temple', count: 1 }, unlockAt: 0, cost: 200000000 },
    { id: 'temple_t2', name: '神圣仪式',  emoji: '🕯️', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'temple', value: 2 },
      desc: '萨满猴产速 ×2', unlockBuilding: { id: 'temple', count: 5 }, unlockAt: 0, cost: 2000000000 },
    { id: 'temple_t3', name: '上古咒术',  emoji: '📿', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'temple', value: 2 },
      desc: '萨满猴产速 ×2', unlockBuilding: { id: 'temple', count: 25 }, unlockAt: 0, cost: 20000000000 },
    { id: 'temple_t4', name: '灵界通道',  emoji: '🌀', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'temple', value: 2 },
      desc: '萨满猴产速 ×2', unlockBuilding: { id: 'temple', count: 50 }, unlockAt: 0, cost: 200000000000 },
    { id: 'temple_t5', name: '神明降临',  emoji: '⚡', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'temple', value: 2 },
      desc: '萨满猴产速 ×2', unlockBuilding: { id: 'temple', count: 100 }, unlockAt: 0, cost: 2000000000000 },

    // ── 巫师猴 (wizard) 分级升级 ─────────────────────
    { id: 'wizard_t1', name: '香蕉魔法',  emoji: '🪄', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'wizard', value: 2 },
      desc: '巫师猴产速 ×2', unlockBuilding: { id: 'wizard', count: 1 }, unlockAt: 0, cost: 3300000000 },
    { id: 'wizard_t2', name: '法师进阶',  emoji: '📖', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'wizard', value: 2 },
      desc: '巫师猴产速 ×2', unlockBuilding: { id: 'wizard', count: 5 }, unlockAt: 0, cost: 33000000000 },
    { id: 'wizard_t3', name: '古老魔典',  emoji: '📚', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'wizard', value: 2 },
      desc: '巫师猴产速 ×2', unlockBuilding: { id: 'wizard', count: 25 }, unlockAt: 0, cost: 330000000000 },
    { id: 'wizard_t4', name: '元素召唤',  emoji: '🔮', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'wizard', value: 2 },
      desc: '巫师猴产速 ×2', unlockBuilding: { id: 'wizard', count: 50 }, unlockAt: 0, cost: 3300000000000 },
    { id: 'wizard_t5', name: '巅峰法力',  emoji: '✨', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'wizard', value: 2 },
      desc: '巫师猴产速 ×2', unlockBuilding: { id: 'wizard', count: 100 }, unlockAt: 0, cost: 33000000000000 },

    // ── 魔法猴 (shipment) 分级升级 ───────────────────
    { id: 'shipment_t1', name: '星际运输',    emoji: '🚀', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'shipment', value: 2 },
      desc: '魔法猴产速 ×2', unlockBuilding: { id: 'shipment', count: 1 }, unlockAt: 0, cost: 51000000000 },
    { id: 'shipment_t2', name: '超时空跳跃',  emoji: '⚡', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'shipment', value: 2 },
      desc: '魔法猴产速 ×2', unlockBuilding: { id: 'shipment', count: 5 }, unlockAt: 0, cost: 510000000000 },
    { id: 'shipment_t3', name: '多维货仓',    emoji: '📦', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'shipment', value: 2 },
      desc: '魔法猴产速 ×2', unlockBuilding: { id: 'shipment', count: 25 }, unlockAt: 0, cost: 5100000000000 },
    { id: 'shipment_t4', name: '宇宙航道',    emoji: '🌌', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'shipment', value: 2 },
      desc: '魔法猴产速 ×2', unlockBuilding: { id: 'shipment', count: 50 }, unlockAt: 0, cost: 51000000000000 },
    { id: 'shipment_t5', name: '光速配送',    emoji: '💫', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'shipment', value: 2 },
      desc: '魔法猴产速 ×2', unlockBuilding: { id: 'shipment', count: 100 }, unlockAt: 0, cost: 510000000000000 },

    // ── 炼金术猴 (alchemy) 分级升级 ──────────────────
    { id: 'alchemy_t1', name: '基础炼金',  emoji: '⚗️', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'alchemy', value: 2 },
      desc: '炼金术猴产速 ×2', unlockBuilding: { id: 'alchemy', count: 1 }, unlockAt: 0, cost: 750000000000 },
    { id: 'alchemy_t2', name: '贤者之石',  emoji: '💎', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'alchemy', value: 2 },
      desc: '炼金术猴产速 ×2', unlockBuilding: { id: 'alchemy', count: 5 }, unlockAt: 0, cost: 7500000000000 },
    { id: 'alchemy_t3', name: '点石成金',  emoji: '✨', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'alchemy', value: 2 },
      desc: '炼金术猴产速 ×2', unlockBuilding: { id: 'alchemy', count: 25 }, unlockAt: 0, cost: 75000000000000 },
    { id: 'alchemy_t4', name: '时空炼化',  emoji: '🔬', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'alchemy', value: 2 },
      desc: '炼金术猴产速 ×2', unlockBuilding: { id: 'alchemy', count: 50 }, unlockAt: 0, cost: 750000000000000 },
    { id: 'alchemy_t5', name: '宇宙炼金',  emoji: '🌟', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'alchemy', value: 2 },
      desc: '炼金术猴产速 ×2', unlockBuilding: { id: 'alchemy', count: 100 }, unlockAt: 0, cost: 7500000000000000 },

    // ── 宇航猴 (portal) 分级升级 ─────────────────────
    { id: 'portal_t1', name: '虫洞开辟',  emoji: '🌀', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'portal', value: 2 },
      desc: '宇航猴产速 ×2', unlockBuilding: { id: 'portal', count: 1 }, unlockAt: 0, cost: 1e13 },
    { id: 'portal_t2', name: '跨维传输',  emoji: '💫', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'portal', value: 2 },
      desc: '宇航猴产速 ×2', unlockBuilding: { id: 'portal', count: 5 }, unlockAt: 0, cost: 1e14 },
    { id: 'portal_t3', name: '时空折叠',  emoji: '⚡', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'portal', value: 2 },
      desc: '宇航猴产速 ×2', unlockBuilding: { id: 'portal', count: 25 }, unlockAt: 0, cost: 1e15 },
    { id: 'portal_t4', name: '次元大门',  emoji: '🚪', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'portal', value: 2 },
      desc: '宇航猴产速 ×2', unlockBuilding: { id: 'portal', count: 50 }, unlockAt: 0, cost: 1e16 },
    { id: 'portal_t5', name: '宇宙传送',  emoji: '🌌', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'portal', value: 2 },
      desc: '宇航猴产速 ×2', unlockBuilding: { id: 'portal', count: 100 }, unlockAt: 0, cost: 1e17 },

    // ── 猴子科学家 (timemachine) 分级升级 ────────────
    { id: 'timemachine_t1', name: '时光瞬移',  emoji: '⏰', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'timemachine', value: 2 },
      desc: '猴子科学家产速 ×2', unlockBuilding: { id: 'timemachine', count: 1 }, unlockAt: 0, cost: 1.4e14 },
    { id: 'timemachine_t2', name: '历史改写',  emoji: '📜', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'timemachine', value: 2 },
      desc: '猴子科学家产速 ×2', unlockBuilding: { id: 'timemachine', count: 5 }, unlockAt: 0, cost: 1.4e15 },
    { id: 'timemachine_t3', name: '平行时空',  emoji: '🔄', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'timemachine', value: 2 },
      desc: '猴子科学家产速 ×2', unlockBuilding: { id: 'timemachine', count: 25 }, unlockAt: 0, cost: 1.4e16 },
    { id: 'timemachine_t4', name: '时间结晶',  emoji: '💎', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'timemachine', value: 2 },
      desc: '猴子科学家产速 ×2', unlockBuilding: { id: 'timemachine', count: 50 }, unlockAt: 0, cost: 1.4e17 },
    { id: 'timemachine_t5', name: '永恒时刻',  emoji: '♾️', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'timemachine', value: 2 },
      desc: '猴子科学家产速 ×2', unlockBuilding: { id: 'timemachine', count: 100 }, unlockAt: 0, cost: 1.4e18 },

    // ── 爱因斯猴 (antimatter) 分级升级 ───────────────
    { id: 'antimatter_t1', name: '反物质萃取',  emoji: '⚛️', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'antimatter', value: 2 },
      desc: '爱因斯猴产速 ×2', unlockBuilding: { id: 'antimatter', count: 1 }, unlockAt: 0, cost: 1.7e15 },
    { id: 'antimatter_t2', name: '湮灭转化',    emoji: '💥', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'antimatter', value: 2 },
      desc: '爱因斯猴产速 ×2', unlockBuilding: { id: 'antimatter', count: 5 }, unlockAt: 0, cost: 1.7e16 },
    { id: 'antimatter_t3', name: '量子纠缠',    emoji: '🔬', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'antimatter', value: 2 },
      desc: '爱因斯猴产速 ×2', unlockBuilding: { id: 'antimatter', count: 25 }, unlockAt: 0, cost: 1.7e17 },
    { id: 'antimatter_t4', name: '超对称理论',  emoji: '🧪', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'antimatter', value: 2 },
      desc: '爱因斯猴产速 ×2', unlockBuilding: { id: 'antimatter', count: 50 }, unlockAt: 0, cost: 1.7e18 },
    { id: 'antimatter_t5', name: '宇宙真理',    emoji: '🌌', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'antimatter', value: 2 },
      desc: '爱因斯猴产速 ×2', unlockBuilding: { id: 'antimatter', count: 100 }, unlockAt: 0, cost: 1.7e19 },

    // ── 哆啦A猴 (prism) 分级升级 ─────────────────────
    { id: 'prism_t1', name: '光谱分解',  emoji: '🌈', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'prism', value: 2 },
      desc: '哆啦A猴产速 ×2', unlockBuilding: { id: 'prism', count: 1 }, unlockAt: 0, cost: 2.1e16 },
    { id: 'prism_t2', name: '彩虹聚焦',  emoji: '✨', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'prism', value: 2 },
      desc: '哆啦A猴产速 ×2', unlockBuilding: { id: 'prism', count: 5 }, unlockAt: 0, cost: 2.1e17 },
    { id: 'prism_t3', name: '光子倍增',  emoji: '💡', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'prism', value: 2 },
      desc: '哆啦A猴产速 ×2', unlockBuilding: { id: 'prism', count: 25 }, unlockAt: 0, cost: 2.1e18 },
    { id: 'prism_t4', name: '虹光满溢',  emoji: '🌟', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'prism', value: 2 },
      desc: '哆啦A猴产速 ×2', unlockBuilding: { id: 'prism', count: 50 }, unlockAt: 0, cost: 2.1e19 },
    { id: 'prism_t5', name: '无限光谱',  emoji: '🌠', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'prism', value: 2 },
      desc: '哆啦A猴产速 ×2', unlockBuilding: { id: 'prism', count: 100 }, unlockAt: 0, cost: 2.1e20 },

    // ── 奥特猴 (chancemaker) 分级升级 ────────────────
    { id: 'chancemaker_t1', name: '幸运本能',  emoji: '🌟', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'chancemaker', value: 2 },
      desc: '奥特猴产速 ×2', unlockBuilding: { id: 'chancemaker', count: 1 }, unlockAt: 0, cost: 2.6e17 },
    { id: 'chancemaker_t2', name: '光之力量',  emoji: '⚡', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'chancemaker', value: 2 },
      desc: '奥特猴产速 ×2', unlockBuilding: { id: 'chancemaker', count: 5 }, unlockAt: 0, cost: 2.6e18 },
    { id: 'chancemaker_t3', name: '奥特能量',  emoji: '💫', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'chancemaker', value: 2 },
      desc: '奥特猴产速 ×2', unlockBuilding: { id: 'chancemaker', count: 25 }, unlockAt: 0, cost: 2.6e19 },
    { id: 'chancemaker_t4', name: '超级进化',  emoji: '🦾', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'chancemaker', value: 2 },
      desc: '奥特猴产速 ×2', unlockBuilding: { id: 'chancemaker', count: 50 }, unlockAt: 0, cost: 2.6e20 },
    { id: 'chancemaker_t5', name: '究极形态',  emoji: '👑', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'chancemaker', value: 2 },
      desc: '奥特猴产速 ×2', unlockBuilding: { id: 'chancemaker', count: 100 }, unlockAt: 0, cost: 2.6e21 },

    // ── 变形猴刚 (fractal) 分级升级 ──────────────────
    { id: 'fractal_t1', name: '分形初现',  emoji: '🔷', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'fractal', value: 2 },
      desc: '变形猴刚产速 ×2', unlockBuilding: { id: 'fractal', count: 1 }, unlockAt: 0, cost: 3.1e18 },
    { id: 'fractal_t2', name: '自相似性',  emoji: '🔀', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'fractal', value: 2 },
      desc: '变形猴刚产速 ×2', unlockBuilding: { id: 'fractal', count: 5 }, unlockAt: 0, cost: 3.1e19 },
    { id: 'fractal_t3', name: '曼德布罗',  emoji: '💫', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'fractal', value: 2 },
      desc: '变形猴刚产速 ×2', unlockBuilding: { id: 'fractal', count: 25 }, unlockAt: 0, cost: 3.1e20 },
    { id: 'fractal_t4', name: '无穷分裂',  emoji: '🌀', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'fractal', value: 2 },
      desc: '变形猴刚产速 ×2', unlockBuilding: { id: 'fractal', count: 50 }, unlockAt: 0, cost: 3.1e21 },
    { id: 'fractal_t5', name: '分形宇宙',  emoji: '🌌', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'fractal', value: 2 },
      desc: '变形猴刚产速 ×2', unlockBuilding: { id: 'fractal', count: 100 }, unlockAt: 0, cost: 3.1e22 },

    // ── java猴 (javascript) 分级升级 ─────────────────
    { id: 'javascript_t1', name: '基础算法',  emoji: '💻', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'javascript', value: 2 },
      desc: 'java猴产速 ×2', unlockBuilding: { id: 'javascript', count: 1 }, unlockAt: 0, cost: 7.1e20 },
    { id: 'javascript_t2', name: '递归优化',  emoji: '🔄', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'javascript', value: 2 },
      desc: 'java猴产速 ×2', unlockBuilding: { id: 'javascript', count: 5 }, unlockAt: 0, cost: 7.1e21 },
    { id: 'javascript_t3', name: '并行计算',  emoji: '⚡', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'javascript', value: 2 },
      desc: 'java猴产速 ×2', unlockBuilding: { id: 'javascript', count: 25 }, unlockAt: 0, cost: 7.1e22 },
    { id: 'javascript_t4', name: '量子编程',  emoji: '🔬', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'javascript', value: 2 },
      desc: 'java猴产速 ×2', unlockBuilding: { id: 'javascript', count: 50 }, unlockAt: 0, cost: 7.1e23 },
    { id: 'javascript_t5', name: '神经网络',  emoji: '🧠', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'javascript', value: 2 },
      desc: 'java猴产速 ×2', unlockBuilding: { id: 'javascript', count: 100 }, unlockAt: 0, cost: 7.1e24 },

    // ── 猴子黑洞 (idleverse) 分级升级 ────────────────
    { id: 'idleverse_t1', name: '引力聚集',  emoji: '🌌', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'idleverse', value: 2 },
      desc: '猴子黑洞产速 ×2', unlockBuilding: { id: 'idleverse', count: 1 }, unlockAt: 0, cost: 1.2e23 },
    { id: 'idleverse_t2', name: '视界扩张',  emoji: '🌀', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'idleverse', value: 2 },
      desc: '猴子黑洞产速 ×2', unlockBuilding: { id: 'idleverse', count: 5 }, unlockAt: 0, cost: 1.2e24 },
    { id: 'idleverse_t3', name: '奇点压缩',  emoji: '💥', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'idleverse', value: 2 },
      desc: '猴子黑洞产速 ×2', unlockBuilding: { id: 'idleverse', count: 25 }, unlockAt: 0, cost: 1.2e25 },
    { id: 'idleverse_t4', name: '闲置剥削',  emoji: '⚡', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'idleverse', value: 2 },
      desc: '猴子黑洞产速 ×2', unlockBuilding: { id: 'idleverse', count: 50 }, unlockAt: 0, cost: 1.2e26 },
    { id: 'idleverse_t5', name: '多元宇宙',  emoji: '🌠', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'idleverse', value: 2 },
      desc: '猴子黑洞产速 ×2', unlockBuilding: { id: 'idleverse', count: 100 }, unlockAt: 0, cost: 1.2e27 },

    // ── 六耳猕猴 (cortex) 分级升级 ───────────────────
    { id: 'cortex_t1', name: '意念初显',  emoji: '🐒', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'cortex', value: 2 },
      desc: '六耳猕猴产速 ×2', unlockBuilding: { id: 'cortex', count: 1 }, unlockAt: 0, cost: 1.9e25 },
    { id: 'cortex_t2', name: '六耳共鸣',  emoji: '🔮', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'cortex', value: 2 },
      desc: '六耳猕猴产速 ×2', unlockBuilding: { id: 'cortex', count: 5 }, unlockAt: 0, cost: 1.9e26 },
    { id: 'cortex_t3', name: '意识扩张',  emoji: '🧠', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'cortex', value: 2 },
      desc: '六耳猕猴产速 ×2', unlockBuilding: { id: 'cortex', count: 25 }, unlockAt: 0, cost: 1.9e27 },
    { id: 'cortex_t4', name: '念力成形',  emoji: '💫', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'cortex', value: 2 },
      desc: '六耳猕猴产速 ×2', unlockBuilding: { id: 'cortex', count: 50 }, unlockAt: 0, cost: 1.9e28 },
    { id: 'cortex_t5', name: '天地同源',  emoji: '👑', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'cortex', value: 2 },
      desc: '六耳猕猴产速 ×2', unlockBuilding: { id: 'cortex', count: 100 }, unlockAt: 0, cost: 1.9e29 },

    // ── 美猴王 (you) 分级升级 ─────────────────────────
    { id: 'you_t1', name: '七十二变',    emoji: '👑', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'you', value: 2 },
      desc: '美猴王产速 ×2', unlockBuilding: { id: 'you', count: 1 }, unlockAt: 0, cost: 3.1e27 },
    { id: 'you_t2', name: '如意金箍棒',  emoji: '🪄', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'you', value: 2 },
      desc: '美猴王产速 ×2', unlockBuilding: { id: 'you', count: 5 }, unlockAt: 0, cost: 3.1e28 },
    { id: 'you_t3', name: '筋斗云',      emoji: '☁️', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'you', value: 2 },
      desc: '美猴王产速 ×2', unlockBuilding: { id: 'you', count: 25 }, unlockAt: 0, cost: 3.1e29 },
    { id: 'you_t4', name: '大闹天宫',    emoji: '⚡', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'you', value: 2 },
      desc: '美猴王产速 ×2', unlockBuilding: { id: 'you', count: 50 }, unlockAt: 0, cost: 3.1e30 },
    { id: 'you_t5', name: '齐天大圣',    emoji: '🌟', category: 'building',
      effect: { type: 'building_cps_mult', buildingId: 'you', value: 2 },
      desc: '美猴王产速 ×2', unlockBuilding: { id: 'you', count: 100 }, unlockAt: 0, cost: 3.1e31 },

    // ── 36个建筑协同升级 ──────────────────────────────
    // 每个协同升级：双向 5% 加成（每拥有对方1个建筑，双方各获得5%产速加成）
    { id: 'syn_cursor_grandma', name: '灵指长老羁绊',       emoji: '🤝', category: 'synergy',
      effect: { type: 'synergy', a: 'cursor', b: 'grandma', pct: 0.05 },
      desc: '光标与智者互相加成，每有1个对方建筑，双方产速各+5%',
      unlockBuilding: { id: 'cursor', count: 1, id2: 'grandma', count2: 1 }, unlockAt: 0, cost: 50000 },
    { id: 'syn_grandma_farm', name: '猴长老田园盟约',       emoji: '🌾', category: 'synergy',
      effect: { type: 'synergy', a: 'grandma', b: 'farm', pct: 0.05 },
      desc: '智者与农工互相加成，每有1个对方建筑，双方产速各+5%',
      unlockBuilding: { id: 'grandma', count: 1, id2: 'farm', count2: 1 }, unlockAt: 0, cost: 550000 },
    { id: 'syn_grandma_mine', name: '岩穴长老盟约',         emoji: '⛏️', category: 'synergy',
      effect: { type: 'synergy', a: 'grandma', b: 'mine', pct: 0.05 },
      desc: '智者与矿工互相加成，每有1个对方建筑，双方产速各+5%',
      unlockBuilding: { id: 'grandma', count: 1, id2: 'mine', count2: 1 }, unlockAt: 0, cost: 6000000 },
    { id: 'syn_grandma_factory', name: '工坊长老盟约',      emoji: '🏭', category: 'synergy',
      effect: { type: 'synergy', a: 'grandma', b: 'factory', pct: 0.05 },
      desc: '智者与员工互相加成，每有1个对方建筑，双方产速各+5%',
      unlockBuilding: { id: 'grandma', count: 1, id2: 'factory', count2: 1 }, unlockAt: 0, cost: 65000000 },
    { id: 'syn_grandma_bank', name: '财阀长老盟约',         emoji: '💰', category: 'synergy',
      effect: { type: 'synergy', a: 'grandma', b: 'bank', pct: 0.05 },
      desc: '智者与收银猴互相加成，每有1个对方建筑，双方产速各+5%',
      unlockBuilding: { id: 'grandma', count: 1, id2: 'bank', count2: 1 }, unlockAt: 0, cost: 700000000 },
    { id: 'syn_grandma_temple', name: '神祀长老盟约',       emoji: '🔮', category: 'synergy',
      effect: { type: 'synergy', a: 'grandma', b: 'temple', pct: 0.05 },
      desc: '智者与萨满猴互相加成，每有1个对方建筑，双方产速各+5%',
      unlockBuilding: { id: 'grandma', count: 1, id2: 'temple', count2: 1 }, unlockAt: 0, cost: 10000000000 },
    { id: 'syn_grandma_wizard', name: '秘术长老盟约',       emoji: '🪄', category: 'synergy',
      effect: { type: 'synergy', a: 'grandma', b: 'wizard', pct: 0.05 },
      desc: '智者与巫师猴互相加成，每有1个对方建筑，双方产速各+5%',
      unlockBuilding: { id: 'grandma', count: 1, id2: 'wizard', count2: 1 }, unlockAt: 0, cost: 165000000000 },
    { id: 'syn_grandma_shipment', name: '星航长老盟约',     emoji: '✨', category: 'synergy',
      effect: { type: 'synergy', a: 'grandma', b: 'shipment', pct: 0.05 },
      desc: '智者与魔法猴互相加成，每有1个对方建筑，双方产速各+5%',
      unlockBuilding: { id: 'grandma', count: 1, id2: 'shipment', count2: 1 }, unlockAt: 0, cost: 2.55e12 },
    { id: 'syn_grandma_alchemy', name: '炼化合盟长老',      emoji: '⚗️', category: 'synergy',
      effect: { type: 'synergy', a: 'grandma', b: 'alchemy', pct: 0.05 },
      desc: '智者与炼金术猴互相加成，每有1个对方建筑，双方产速各+5%',
      unlockBuilding: { id: 'grandma', count: 1, id2: 'alchemy', count2: 1 }, unlockAt: 0, cost: 3.75e13 },
    { id: 'syn_grandma_portal', name: '异界长老盟约',       emoji: '🚀', category: 'synergy',
      effect: { type: 'synergy', a: 'grandma', b: 'portal', pct: 0.05 },
      desc: '智者与宇航猴互相加成，每有1个对方建筑，双方产速各+5%',
      unlockBuilding: { id: 'grandma', count: 1, id2: 'portal', count2: 1 }, unlockAt: 0, cost: 5e14 },
    { id: 'syn_grandma_timemachine', name: '时序长老盟约',  emoji: '⏰', category: 'synergy',
      effect: { type: 'synergy', a: 'grandma', b: 'timemachine', pct: 0.05 },
      desc: '智者与猴子科学家互相加成，每有1个对方建筑，双方产速各+5%',
      unlockBuilding: { id: 'grandma', count: 1, id2: 'timemachine', count2: 1 }, unlockAt: 0, cost: 7e15 },
    { id: 'syn_grandma_antimatter', name: '暗物质长老之契', emoji: '⚛️', category: 'synergy',
      effect: { type: 'synergy', a: 'grandma', b: 'antimatter', pct: 0.05 },
      desc: '智者与爱因斯猴互相加成，每有1个对方建筑，双方产速各+5%',
      unlockBuilding: { id: 'grandma', count: 1, id2: 'antimatter', count2: 1 }, unlockAt: 0, cost: 8.5e16 },
    { id: 'syn_grandma_prism', name: '虹光长老之契',        emoji: '🌈', category: 'synergy',
      effect: { type: 'synergy', a: 'grandma', b: 'prism', pct: 0.05 },
      desc: '智者与哆啦A猴互相加成，每有1个对方建筑，双方产速各+5%',
      unlockBuilding: { id: 'grandma', count: 1, id2: 'prism', count2: 1 }, unlockAt: 0, cost: 1.05e18 },
    { id: 'syn_grandma_chancemaker', name: '鸿运长老之契',  emoji: '🌟', category: 'synergy',
      effect: { type: 'synergy', a: 'grandma', b: 'chancemaker', pct: 0.05 },
      desc: '智者与奥特猴互相加成，每有1个对方建筑，双方产速各+5%',
      unlockBuilding: { id: 'grandma', count: 1, id2: 'chancemaker', count2: 1 }, unlockAt: 0, cost: 1.3e19 },
    { id: 'syn_grandma_fractal', name: '分形长老之契',      emoji: '🔷', category: 'synergy',
      effect: { type: 'synergy', a: 'grandma', b: 'fractal', pct: 0.05 },
      desc: '智者与变形猴刚互相加成，每有1个对方建筑，双方产速各+5%',
      unlockBuilding: { id: 'grandma', count: 1, id2: 'fractal', count2: 1 }, unlockAt: 0, cost: 1.55e20 },
    { id: 'syn_grandma_javascript', name: '代码长老之契',   emoji: '💻', category: 'synergy',
      effect: { type: 'synergy', a: 'grandma', b: 'javascript', pct: 0.05 },
      desc: '智者与java猴互相加成，每有1个对方建筑，双方产速各+5%',
      unlockBuilding: { id: 'grandma', count: 1, id2: 'javascript', count2: 1 }, unlockAt: 0, cost: 3.55e22 },
    { id: 'syn_grandma_idleverse', name: '虚空长老之契',    emoji: '🌌', category: 'synergy',
      effect: { type: 'synergy', a: 'grandma', b: 'idleverse', pct: 0.05 },
      desc: '智者与猴子黑洞互相加成，每有1个对方建筑，双方产速各+5%',
      unlockBuilding: { id: 'grandma', count: 1, id2: 'idleverse', count2: 1 }, unlockAt: 0, cost: 6e24 },
    { id: 'syn_grandma_cortex', name: '灵脑长老之契',       emoji: '🐒', category: 'synergy',
      effect: { type: 'synergy', a: 'grandma', b: 'cortex', pct: 0.05 },
      desc: '智者与六耳猕猴互相加成，每有1个对方建筑，双方产速各+5%',
      unlockBuilding: { id: 'grandma', count: 1, id2: 'cortex', count2: 1 }, unlockAt: 0, cost: 9.5e26 },
    { id: 'syn_grandma_you', name: '大圣血亲之契',          emoji: '👑', category: 'synergy',
      effect: { type: 'synergy', a: 'grandma', b: 'you', pct: 0.05 },
      desc: '智者与美猴王互相加成，每有1个对方建筑，双方产速各+5%',
      unlockBuilding: { id: 'grandma', count: 1, id2: 'you', count2: 1 }, unlockAt: 0, cost: 1.55e29 },
    { id: 'syn_farm_mine', name: '灵田矿脉共生',            emoji: '🌾', category: 'synergy',
      effect: { type: 'synergy', a: 'farm', b: 'mine', pct: 0.05 },
      desc: '农工与矿工互相加成，每有1个对方建筑，双方产速各+5%',
      unlockBuilding: { id: 'farm', count: 1, id2: 'mine', count2: 1 }, unlockAt: 0, cost: 6000000 },
    { id: 'syn_mine_factory', name: '熔炉矿工同盟',         emoji: '⛏️', category: 'synergy',
      effect: { type: 'synergy', a: 'mine', b: 'factory', pct: 0.05 },
      desc: '矿工与员工互相加成，每有1个对方建筑，双方产速各+5%',
      unlockBuilding: { id: 'mine', count: 1, id2: 'factory', count2: 1 }, unlockAt: 0, cost: 65000000 },
    { id: 'syn_factory_bank', name: '工企金融同盟',         emoji: '🏭', category: 'synergy',
      effect: { type: 'synergy', a: 'factory', b: 'bank', pct: 0.05 },
      desc: '员工与收银猴互相加成，每有1个对方建筑，双方产速各+5%',
      unlockBuilding: { id: 'factory', count: 1, id2: 'bank', count2: 1 }, unlockAt: 0, cost: 700000000 },
    { id: 'syn_bank_temple', name: '金殿神祀共生',          emoji: '💰', category: 'synergy',
      effect: { type: 'synergy', a: 'bank', b: 'temple', pct: 0.05 },
      desc: '收银猴与萨满猴互相加成，每有1个对方建筑，双方产速各+5%',
      unlockBuilding: { id: 'bank', count: 1, id2: 'temple', count2: 1 }, unlockAt: 0, cost: 10000000000 },
    { id: 'syn_temple_wizard', name: '神祭秘术同盟',        emoji: '🔮', category: 'synergy',
      effect: { type: 'synergy', a: 'temple', b: 'wizard', pct: 0.05 },
      desc: '萨满猴与巫师猴互相加成，每有1个对方建筑，双方产速各+5%',
      unlockBuilding: { id: 'temple', count: 1, id2: 'wizard', count2: 1 }, unlockAt: 0, cost: 165000000000 },
    { id: 'syn_wizard_shipment', name: '魔航星际同盟',      emoji: '🪄', category: 'synergy',
      effect: { type: 'synergy', a: 'wizard', b: 'shipment', pct: 0.05 },
      desc: '巫师猴与魔法猴互相加成，每有1个对方建筑，双方产速各+5%',
      unlockBuilding: { id: 'wizard', count: 1, id2: 'shipment', count2: 1 }, unlockAt: 0, cost: 2.55e12 },
    { id: 'syn_shipment_alchemy', name: '星舟炼金共生',     emoji: '✨', category: 'synergy',
      effect: { type: 'synergy', a: 'shipment', b: 'alchemy', pct: 0.05 },
      desc: '魔法猴与炼金术猴互相加成，每有1个对方建筑，双方产速各+5%',
      unlockBuilding: { id: 'shipment', count: 1, id2: 'alchemy', count2: 1 }, unlockAt: 0, cost: 3.75e13 },
    { id: 'syn_alchemy_portal', name: '炼界门扉同盟',       emoji: '⚗️', category: 'synergy',
      effect: { type: 'synergy', a: 'alchemy', b: 'portal', pct: 0.05 },
      desc: '炼金术猴与宇航猴互相加成，每有1个对方建筑，双方产速各+5%',
      unlockBuilding: { id: 'alchemy', count: 1, id2: 'portal', count2: 1 }, unlockAt: 0, cost: 5e14 },
    { id: 'syn_portal_timemachine', name: '时空界域共生',   emoji: '🚀', category: 'synergy',
      effect: { type: 'synergy', a: 'portal', b: 'timemachine', pct: 0.05 },
      desc: '宇航猴与猴子科学家互相加成，每有1个对方建筑，双方产速各+5%',
      unlockBuilding: { id: 'portal', count: 1, id2: 'timemachine', count2: 1 }, unlockAt: 0, cost: 7e15 },
    { id: 'syn_timemachine_antimatter', name: '时序暗能同盟', emoji: '⏰', category: 'synergy',
      effect: { type: 'synergy', a: 'timemachine', b: 'antimatter', pct: 0.05 },
      desc: '科学家与爱因斯猴互相加成，每有1个对方建筑，双方产速各+5%',
      unlockBuilding: { id: 'timemachine', count: 1, id2: 'antimatter', count2: 1 }, unlockAt: 0, cost: 8.5e16 },
    { id: 'syn_antimatter_prism', name: '反物质虹光共生',   emoji: '⚛️', category: 'synergy',
      effect: { type: 'synergy', a: 'antimatter', b: 'prism', pct: 0.05 },
      desc: '爱因斯猴与哆啦A猴互相加成，每有1个对方建筑，双方产速各+5%',
      unlockBuilding: { id: 'antimatter', count: 1, id2: 'prism', count2: 1 }, unlockAt: 0, cost: 1.05e18 },
    { id: 'syn_prism_chancemaker', name: '彩光鸿运同盟',    emoji: '🌈', category: 'synergy',
      effect: { type: 'synergy', a: 'prism', b: 'chancemaker', pct: 0.05 },
      desc: '哆啦A猴与奥特猴互相加成，每有1个对方建筑，双方产速各+5%',
      unlockBuilding: { id: 'prism', count: 1, id2: 'chancemaker', count2: 1 }, unlockAt: 0, cost: 1.3e19 },
    { id: 'syn_chancemaker_fractal', name: '气运分形共生',  emoji: '🌟', category: 'synergy',
      effect: { type: 'synergy', a: 'chancemaker', b: 'fractal', pct: 0.05 },
      desc: '奥特猴与变形猴刚互相加成，每有1个对方建筑，双方产速各+5%',
      unlockBuilding: { id: 'chancemaker', count: 1, id2: 'fractal', count2: 1 }, unlockAt: 0, cost: 1.55e20 },
    { id: 'syn_fractal_javascript', name: '碎形代码同盟',   emoji: '🔷', category: 'synergy',
      effect: { type: 'synergy', a: 'fractal', b: 'javascript', pct: 0.05 },
      desc: '变形猴刚与java猴互相加成，每有1个对方建筑，双方产速各+5%',
      unlockBuilding: { id: 'fractal', count: 1, id2: 'javascript', count2: 1 }, unlockAt: 0, cost: 3.55e22 },
    { id: 'syn_javascript_idleverse', name: '虚数代码共生', emoji: '💻', category: 'synergy',
      effect: { type: 'synergy', a: 'javascript', b: 'idleverse', pct: 0.05 },
      desc: 'java猴与猴子黑洞互相加成，每有1个对方建筑，双方产速各+5%',
      unlockBuilding: { id: 'javascript', count: 1, id2: 'idleverse', count2: 1 }, unlockAt: 0, cost: 6e24 },
    { id: 'syn_idleverse_cortex', name: '虚空灵脑同盟',     emoji: '🌌', category: 'synergy',
      effect: { type: 'synergy', a: 'idleverse', b: 'cortex', pct: 0.05 },
      desc: '猴子黑洞与六耳猕猴互相加成，每有1个对方建筑，双方产速各+5%',
      unlockBuilding: { id: 'idleverse', count: 1, id2: 'cortex', count2: 1 }, unlockAt: 0, cost: 9.5e26 },
    { id: 'syn_cortex_you', name: '神脑大圣共生',           emoji: '🐒', category: 'synergy',
      effect: { type: 'synergy', a: 'cortex', b: 'you', pct: 0.05 },
      desc: '六耳猕猴与美猴王互相加成，每有1个对方建筑，双方产速各+5%',
      unlockBuilding: { id: 'cortex', count: 1, id2: 'you', count2: 1 }, unlockAt: 0, cost: 1.55e29 },

    // ── 18个长老变种升级 ──────────────────────────────
    // 效果：猴子智者产速 ×2，且每拥有1个智者，关联建筑产速+2%
    { id: 'gv_farm', name: '灵田猴长老',       emoji: '🌾', category: 'grandma',
      effect: { type: 'grandma_variant', buildingId: 'farm', grandmaBoost: 2, linkedBoost: 0.02 },
      desc: '猴子智者产速 ×2；每拥有1个智者，猴子农工产速+2%',
      unlockBuilding: { id: 'grandma', count: 1, id2: 'farm', count2: 1 }, unlockAt: 0, cost: 220000 },
    { id: 'gv_mine', name: '掘矿猴长老',       emoji: '⛏️', category: 'grandma',
      effect: { type: 'grandma_variant', buildingId: 'mine', grandmaBoost: 2, linkedBoost: 0.02 },
      desc: '猴子智者产速 ×2；每拥有1个智者，猴子矿工产速+2%',
      unlockBuilding: { id: 'grandma', count: 1, id2: 'mine', count2: 1 }, unlockAt: 0, cost: 2400000 },
    { id: 'gv_factory', name: '工造猴长老',    emoji: '🏭', category: 'grandma',
      effect: { type: 'grandma_variant', buildingId: 'factory', grandmaBoost: 2, linkedBoost: 0.02 },
      desc: '猴子智者产速 ×2；每拥有1个智者，猴子员工产速+2%',
      unlockBuilding: { id: 'grandma', count: 1, id2: 'factory', count2: 1 }, unlockAt: 0, cost: 26000000 },
    { id: 'gv_bank', name: '聚宝猴长老',       emoji: '💰', category: 'grandma',
      effect: { type: 'grandma_variant', buildingId: 'bank', grandmaBoost: 2, linkedBoost: 0.02 },
      desc: '猴子智者产速 ×2；每拥有1个智者，收银猴产速+2%',
      unlockBuilding: { id: 'grandma', count: 1, id2: 'bank', count2: 1 }, unlockAt: 0, cost: 280000000 },
    { id: 'gv_temple', name: '祭神猴长老',     emoji: '🔮', category: 'grandma',
      effect: { type: 'grandma_variant', buildingId: 'temple', grandmaBoost: 2, linkedBoost: 0.02 },
      desc: '猴子智者产速 ×2；每拥有1个智者，萨满猴产速+2%',
      unlockBuilding: { id: 'grandma', count: 1, id2: 'temple', count2: 1 }, unlockAt: 0, cost: 4000000000 },
    { id: 'gv_wizard', name: '妖法猴长老',     emoji: '🪄', category: 'grandma',
      effect: { type: 'grandma_variant', buildingId: 'wizard', grandmaBoost: 2, linkedBoost: 0.02 },
      desc: '猴子智者产速 ×2；每拥有1个智者，巫师猴产速+2%',
      unlockBuilding: { id: 'grandma', count: 1, id2: 'wizard', count2: 1 }, unlockAt: 0, cost: 66000000000 },
    { id: 'gv_shipment', name: '星河猴长老',   emoji: '✨', category: 'grandma',
      effect: { type: 'grandma_variant', buildingId: 'shipment', grandmaBoost: 2, linkedBoost: 0.02 },
      desc: '猴子智者产速 ×2；每拥有1个智者，魔法猴产速+2%',
      unlockBuilding: { id: 'grandma', count: 1, id2: 'shipment', count2: 1 }, unlockAt: 0, cost: 1.02e12 },
    { id: 'gv_alchemy', name: '锻炼猴长老',   emoji: '⚗️', category: 'grandma',
      effect: { type: 'grandma_variant', buildingId: 'alchemy', grandmaBoost: 2, linkedBoost: 0.02 },
      desc: '猴子智者产速 ×2；每拥有1个智者，炼金术猴产速+2%',
      unlockBuilding: { id: 'grandma', count: 1, id2: 'alchemy', count2: 1 }, unlockAt: 0, cost: 1.5e13 },
    { id: 'gv_portal', name: '异次元猴长老',   emoji: '🚀', category: 'grandma',
      effect: { type: 'grandma_variant', buildingId: 'portal', grandmaBoost: 2, linkedBoost: 0.02 },
      desc: '猴子智者产速 ×2；每拥有1个智者，宇航猴产速+2%',
      unlockBuilding: { id: 'grandma', count: 1, id2: 'portal', count2: 1 }, unlockAt: 0, cost: 2e14 },
    { id: 'gv_timemachine', name: '溯时猴长老', emoji: '⏰', category: 'grandma',
      effect: { type: 'grandma_variant', buildingId: 'timemachine', grandmaBoost: 2, linkedBoost: 0.02 },
      desc: '猴子智者产速 ×2；每拥有1个智者，猴子科学家产速+2%',
      unlockBuilding: { id: 'grandma', count: 1, id2: 'timemachine', count2: 1 }, unlockAt: 0, cost: 2.8e15 },
    { id: 'gv_antimatter', name: '暗核猴长老', emoji: '⚛️', category: 'grandma',
      effect: { type: 'grandma_variant', buildingId: 'antimatter', grandmaBoost: 2, linkedBoost: 0.02 },
      desc: '猴子智者产速 ×2；每拥有1个智者，爱因斯猴产速+2%',
      unlockBuilding: { id: 'grandma', count: 1, id2: 'antimatter', count2: 1 }, unlockAt: 0, cost: 3.4e16 },
    { id: 'gv_prism', name: '幻彩猴长老',     emoji: '🌈', category: 'grandma',
      effect: { type: 'grandma_variant', buildingId: 'prism', grandmaBoost: 2, linkedBoost: 0.02 },
      desc: '猴子智者产速 ×2；每拥有1个智者，哆啦A猴产速+2%',
      unlockBuilding: { id: 'grandma', count: 1, id2: 'prism', count2: 1 }, unlockAt: 0, cost: 4.2e17 },
    { id: 'gv_chancemaker', name: '天命猴长老', emoji: '🌟', category: 'grandma',
      effect: { type: 'grandma_variant', buildingId: 'chancemaker', grandmaBoost: 2, linkedBoost: 0.02 },
      desc: '猴子智者产速 ×2；每拥有1个智者，奥特猴产速+2%',
      unlockBuilding: { id: 'grandma', count: 1, id2: 'chancemaker', count2: 1 }, unlockAt: 0, cost: 5.2e18 },
    { id: 'gv_fractal', name: '多维猴长老',    emoji: '🔷', category: 'grandma',
      effect: { type: 'grandma_variant', buildingId: 'fractal', grandmaBoost: 2, linkedBoost: 0.02 },
      desc: '猴子智者产速 ×2；每拥有1个智者，变形猴刚产速+2%',
      unlockBuilding: { id: 'grandma', count: 1, id2: 'fractal', count2: 1 }, unlockAt: 0, cost: 6.2e19 },
    { id: 'gv_javascript', name: '代码猴长老', emoji: '💻', category: 'grandma',
      effect: { type: 'grandma_variant', buildingId: 'javascript', grandmaBoost: 2, linkedBoost: 0.02 },
      desc: '猴子智者产速 ×2；每拥有1个智者，java猴产速+2%',
      unlockBuilding: { id: 'grandma', count: 1, id2: 'javascript', count2: 1 }, unlockAt: 0, cost: 1.42e22 },
    { id: 'gv_idleverse', name: '太虚猴长老',  emoji: '🌌', category: 'grandma',
      effect: { type: 'grandma_variant', buildingId: 'idleverse', grandmaBoost: 2, linkedBoost: 0.02 },
      desc: '猴子智者产速 ×2；每拥有1个智者，猴子黑洞产速+2%',
      unlockBuilding: { id: 'grandma', count: 1, id2: 'idleverse', count2: 1 }, unlockAt: 0, cost: 2.4e24 },
    { id: 'gv_cortex', name: '神念猴长老',    emoji: '🐒', category: 'grandma',
      effect: { type: 'grandma_variant', buildingId: 'cortex', grandmaBoost: 2, linkedBoost: 0.02 },
      desc: '猴子智者产速 ×2；每拥有1个智者，六耳猕猴产速+2%',
      unlockBuilding: { id: 'grandma', count: 1, id2: 'cortex', count2: 1 }, unlockAt: 0, cost: 3.8e26 },
    { id: 'gv_you', name: '齐天猴长老',       emoji: '👑', category: 'grandma',
      effect: { type: 'grandma_variant', buildingId: 'you', grandmaBoost: 2, linkedBoost: 0.02 },
      desc: '猴子智者产速 ×2；每拥有1个智者，美猴王产速+2%',
      unlockBuilding: { id: 'grandma', count: 1, id2: 'you', count2: 1 }, unlockAt: 0, cost: 6.2e27 },
  ],

  saveVersion: 3,
  mailInboxLimit: 50,

  bananaStyles: [
    { id: 'yellow', name: '黄香蕉', emoji: '🍌', cssClass: '',           price: 0 },
    { id: 'green',  name: '青香蕉', emoji: '🍌', cssClass: 'style-green', price: 500 },
    { id: 'red',    name: '红香蕉', emoji: '🍌', cssClass: 'style-red',   price: 2000 },
    { id: 'blue',   name: '蓝香蕉', emoji: '🍌', cssClass: 'style-blue',  price: 10000 },
  ],
});
